{% set name = "pyspeckit" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41e26b850de1f1b22cbfe630409aae0ac5beb585a214e06225f15c37872db886
  patches:
    - setup.py.patch
    - setup.cfg.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - astropy
    - matplotlib >=1.4
    - numpy
    - python

test:
  imports:
    - pyspeckit
    - pyspeckit.cubes
    - pyspeckit.mpfit
    - pyspeckit.parallel_map
    - pyspeckit.spectrum
    - pyspeckit.spectrum.models
    - pyspeckit.spectrum.readers
    - pyspeckit.spectrum.speclines
    - pyspeckit.spectrum.utils
    - pyspeckit.spectrum.writers
    - pyspeckit.wrappers

about:
  home: http://pyspeckit.readthedocs.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Toolkit for fitting and manipulating spectroscopic data in python
  doc_url: http://pyspeckit.readthedocs.org
  dev_url: https://github.com/pyspeckit/pyspeckit

extra:
  recipe-maintainers:
    - mwcraig
    - keflavich
