travis:
  secure:
    BINSTAR_TOKEN: lK7lPmVzZeghLB4Qvk2DeJ61vaPhJEd6l1zN6YT+l1j1EfJm+P01mQZfWURZkigKWhmKIF5RBZWRa61LocV7bukja/f5zGfQZkHYFYMYEAKi2AzUV9lxu0xcbQJNLL4CU4GTTjf+gAIasrxkSy3zgLOj4OW3Lyj+tE16VlhTF7YUHYhV9+oyzjD1PIZdOxGfxl0ct2FFDS3wivhCrc9OKpR3p/e8EIZqq5XVdfPoU1Lsxxj0VjGmDHSMVpCACLrnJMbMy4QEM9+su67PtjCSbn1ZxphxwTVYK+yZ8Exd2VMEewDgVEijUHuigW/m2igFX2r7OsH6kv/p987hIf3SWaCDeTas2jL9MmS9PboaR1xYnB8V7wRaKe6m+SKugmM2Mf3JLkVPcFbK+si+HI3BD5dS2AKbah2gLxhr0mqL3lZLvoEFVhZ7X5ovEmYyPRPk0G7GySnUJStl4oaptTyoDXUClJERHwm15X0u0pr2DzuXMA06at7YLg6cqocEUNsm5oxsSQKTvn/H929MOHTfdrjMbKpFvBDhkfPAjn/IDUvDABVt3yHH+r41fAU3EpeXDl77sy8ku6fMZoO9OyoGLOkoi7jqBRPEWzHnnEVkdG//xSj2qvtwzQSi9pv3fYdryOsZvPcUycp9qDTvLxZZJcSqXob4vtr52ONAnd46zvg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
